 import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MyWorld3 here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MyWorld3 extends World
{

    /**
     * Constructor for objects of class MyWorld3.
     * 
     */
    public MyWorld3()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(600, 600, 1);
        prepare();
    }
    
    private void prepare()
    {
        WallHeightLong wallHeightLong = new WallHeightLong();
        addObject(wallHeightLong,13,101);
        wallHeightLong.setLocation(10,95);
        WallHeightLong wallHeightLong2 = new WallHeightLong();
        addObject(wallHeightLong2,16,283);
        wallHeightLong2.setLocation(10,270);
        WallHeightLong wallHeightLong3 = new WallHeightLong();
        addObject(wallHeightLong3,11,475);
        wallHeightLong3.setLocation(10,450);
        WallWidthLong wallWidthLong = new WallWidthLong();
        addObject(wallWidthLong,108,8);
        wallWidthLong.setLocation(108,11);
        WallWidthSmall wallWidthSmall = new WallWidthSmall();
        addObject(wallWidthSmall,222,12);
        wallWidthSmall.setLocation(220,8);
        WallHeightLong wallHeightLong4 = new WallHeightLong();
        addObject(wallHeightLong4,592,69);
        wallHeightLong4.setLocation(589,92);
        WallHeightLong wallHeightLong5 = new WallHeightLong();
        addObject(wallHeightLong5,590,286);
        wallHeightLong5.setLocation(589,272);
        WallHeightLong wallHeightLong6 = new WallHeightLong();
        addObject(wallHeightLong6,591,456);
        wallHeightLong6.setLocation(588,451);
        WallWidthLong wallWidthLong2 = new WallWidthLong();
        addObject(wallWidthLong2,514,13);
        wallWidthLong2.setLocation(491,10);
        WallWidthMedium wallWidthMedium = new WallWidthMedium();
        addObject(wallWidthMedium,348,6);
        wallWidthMedium.setLocation(352,10);

        WallWidthLong wallWidthLong3 = new WallWidthLong();
        addObject(wallWidthLong3,503,588);
        wallWidthLong3.setLocation(522,587);
        WallWidthSmall wallWidthSmall2 = new WallWidthSmall();
        addObject(wallWidthSmall2,391,591);
        wallWidthSmall2.setLocation(390,591);
        removeObject(wallWidthSmall2);
        WallWidthMedium wallWidthMedium2 = new WallWidthMedium();
        addObject(wallWidthMedium2,416,587);
        wallWidthMedium2.setLocation(409,588);
        WallHeightSmall wallHeightSmall = new WallHeightSmall();
        addObject(wallHeightSmall,590,565);
        wallHeightSmall.setLocation(589,561);
        WallHeightSmall wallHeightSmall2 = new WallHeightSmall();
        addObject(wallHeightSmall2,18,566);
        wallHeightSmall2.setLocation(10,564);
        WallWidthLong wallWidthLong4 = new WallWidthLong();
        addObject(wallWidthLong4,58,591);
        wallWidthLong4.setLocation(95,587);
        WallWidthLong wallWidthLong5 = new WallWidthLong();
        addObject(wallWidthLong5,250,589);
        wallWidthLong5.setLocation(220,586);
        WallHeightSmall wallHeightSmall3 = new WallHeightSmall();
        addObject(wallHeightSmall3,238,35);
        wallHeightSmall3.setLocation(242,46);
        WallHeightSmall wallHeightSmall4 = new WallHeightSmall();
        addObject(wallHeightSmall4,416,45);
        wallHeightSmall4.setLocation(416,49);
        WallWidthSmall wallWidthSmall3 = new WallWidthSmall();
        addObject(wallWidthSmall3,44,241);
        wallWidthSmall3.setLocation(48,241);
        WallWidthSmall wallWidthSmall4 = new WallWidthSmall();
        addObject(wallWidthSmall4,48,357);
        WallWidthSmall wallWidthSmall5 = new WallWidthSmall();
        addObject(wallWidthSmall5,49,471);
        wallWidthSmall5.setLocation(48,471);
        WallWidthSmall wallWidthSmall6 = new WallWidthSmall();
        addObject(wallWidthSmall6,553,297);
        wallWidthSmall6.setLocation(554,301);
        wallWidthSmall6.setLocation(552,299);
        WallHeightSmall wallHeightSmall5 = new WallHeightSmall();
        addObject(wallHeightSmall5,308,557);
        wallHeightSmall5.setLocation(299,552);
        WallWidthLong wallWidthLong6 = new WallWidthLong();
        addObject(wallWidthLong6,398,531);
        wallWidthLong6.setLocation(393,531);
        WallHeightLong wallHeightLong7 = new WallHeightLong();
        addObject(wallHeightLong7,537,65);
        wallHeightLong7.setLocation(532,110);
        WallHeightSmall wallHeightSmall6 = new WallHeightSmall();
        addObject(wallHeightSmall6,528,214);
        wallHeightSmall6.setLocation(533,222);
        WallWidthMedium wallWidthMedium3 = new WallWidthMedium();
        addObject(wallWidthMedium3,440,185);
        removeObject(wallWidthMedium3);
        WallWidthLong wallWidthLong7 = new WallWidthLong();
        addObject(wallWidthLong7,426,182);
        wallWidthLong7.setLocation(440,184);
        WallHeightLong wallHeightLong8 = new WallHeightLong();
        addObject(wallHeightLong8,183,522);
        wallHeightLong8.setLocation(186,491);
        WallHeightSmall wallHeightSmall7 = new WallHeightSmall();
        addObject(wallHeightSmall7,186,380);
        wallHeightSmall7.setLocation(183,381);
        WallWidthSmall wallWidthSmall7 = new WallWidthSmall();
        addObject(wallWidthSmall7,155,472);
        wallWidthSmall7.setLocation(149,472);
        WallHeightSmall wallHeightSmall8 = new WallHeightSmall();
        addObject(wallHeightSmall8,126,511);
        wallHeightSmall8.setLocation(126,509);
        WallWidthSmall wallWidthSmall8 = new WallWidthSmall();
        addObject(wallWidthSmall8,92,529);
        wallWidthSmall8.setLocation(90,531);
        WallHeightSmall wallHeightSmall9 = new WallHeightSmall();
        addObject(wallHeightSmall9,61,443);
        wallHeightSmall9.setLocation(67,435);
        WallWidthSmall wallWidthSmall9 = new WallWidthSmall();
        addObject(wallWidthSmall9,105,412);
        wallWidthSmall9.setLocation(105,412);
        WallHeightLong wallHeightLong9 = new WallHeightLong();
        addObject(wallHeightLong9,132,360);
        wallHeightLong9.setLocation(128,315);
        WallHeightMedium wallHeightMedium = new WallHeightMedium();
        addObject(wallHeightMedium,130,153);
        wallHeightMedium.setLocation(128,177);
        WallWidthSmall wallWidthSmall10 = new WallWidthSmall();
        addObject(wallWidthSmall10,105,302);
        wallWidthSmall10.setLocation(92,300);
        WallWidthSmall wallWidthSmall11 = new WallWidthSmall();
        addObject(wallWidthSmall11,158,300);
        wallWidthSmall11.setLocation(163,300);
        WallWidthMedium wallWidthMedium4 = new WallWidthMedium();
        addObject(wallWidthMedium4,188,128);
        wallWidthMedium4.setLocation(192,125);
        WallHeightSmall wallHeightSmall10 = new WallHeightSmall();
        addObject(wallHeightSmall10,185,95);
        wallHeightSmall10.setLocation(185,89);
        WallHeightMedium wallHeightMedium2 = new WallHeightMedium();
        addObject(wallHeightMedium2,123,65);
        removeObject(wallHeightMedium2);
        WallWidthMedium wallWidthMedium5 = new WallWidthMedium();
        addObject(wallWidthMedium5,117,69);
        wallWidthMedium5.setLocation(120,67);
        WallHeightMedium wallHeightMedium3 = new WallHeightMedium();
        addObject(wallHeightMedium3,79,131);
        wallHeightMedium3.setLocation(67,133);

        WallHeightLong wallHeightLong10 = new WallHeightLong();
        addObject(wallHeightLong10,529,508);
        wallHeightLong10.setLocation(532,491);
        WallHeightSmall wallHeightSmall11 = new WallHeightSmall();
        addObject(wallHeightSmall11,535,375);
        wallHeightSmall11.setLocation(532,379);
        WallWidthLong wallWidthLong8 = new WallWidthLong();
        addObject(wallWidthLong8,477,471);
        wallWidthLong8.setLocation(435,473);

        WallWidthMedium wallWidthMedium6 = new WallWidthMedium();
        addObject(wallWidthMedium6,289,475);
        wallWidthMedium6.setLocation(296,473);
        WallHeightSmall wallHeightSmall12 = new WallHeightSmall();
        addObject(wallHeightSmall12,239,505);
        wallHeightSmall12.setLocation(243,511);
        WallWidthSmall wallWidthSmall12 = new WallWidthSmall();
        addObject(wallWidthSmall12,501,414);
        wallWidthSmall12.setLocation(495,415);
        WallHeightSmall wallHeightSmall13 = new WallHeightSmall();
        addObject(wallHeightSmall13,300,440);
        wallHeightSmall13.setLocation(299,436);
        WallHeightLong wallHeightLong11 = new WallHeightLong();
        addObject(wallHeightLong11,239,427);
        wallHeightLong11.setLocation(243,377);

        WallHeightSmall wallHeightSmall14 = new WallHeightSmall();
        addObject(wallHeightSmall14,242,260);
        wallHeightSmall14.setLocation(243,261);
        WallWidthSmall wallWidthSmall13 = new WallWidthSmall();
        addObject(wallWidthSmall13,201,244);
        wallWidthSmall13.setLocation(206,238);
        WallHeightSmall wallHeightSmall15 = new WallHeightSmall();
        addObject(wallHeightSmall15,185,202);
        wallHeightSmall15.setLocation(183,205);
        WallHeightSmall wallHeightSmall16 = new WallHeightSmall();
        addObject(wallHeightSmall16,249,156);
        wallHeightSmall16.setLocation(243,161);
        WallWidthSmall wallWidthSmall14 = new WallWidthSmall();
        addObject(wallWidthSmall14,273,180);
        wallWidthSmall14.setLocation(280,184);
        WallHeightLong wallHeightLong12 = new WallHeightLong();
        addObject(wallHeightLong12,304,258);
        wallHeightLong12.setLocation(302,276);
        WallHeightSmall wallHeightSmall17 = new WallHeightSmall();
        addObject(wallHeightSmall17,301,157);
        wallHeightSmall17.setLocation(302,148);

        WallWidthLong wallWidthLong9 = new WallWidthLong();
        addObject(wallWidthLong9,393,125);
        WallHeightSmall wallHeightSmall18 = new WallHeightSmall();
        addObject(wallHeightSmall18,476,78);
        wallHeightSmall18.setLocation(475,90);
        WallHeightSmall wallHeightSmall19 = new WallHeightSmall();
        addObject(wallHeightSmall19,358,85);
        wallHeightSmall19.setLocation(359,89);
        WallWidthSmall wallWidthSmall15 = new WallWidthSmall();
        addObject(wallWidthSmall15,323,66);
        wallWidthSmall15.setLocation(321,66);
        WallHeightSmall wallHeightSmall20 = new WallHeightSmall();
        addObject(wallHeightSmall20,415,217);
        wallHeightSmall20.setLocation(415,221);
        WallWidthSmall wallWidthSmall16 = new WallWidthSmall();
        addObject(wallWidthSmall16,331,239);
        wallWidthSmall16.setLocation(337,240);
        WallWidthSmall wallWidthSmall17 = new WallWidthSmall();
        addObject(wallWidthSmall17,327,356);
        wallWidthSmall17.setLocation(337,359);
        WallHeightSmall wallHeightSmall21 = new WallHeightSmall();
        addObject(wallHeightSmall21,353,392);
        wallHeightSmall21.setLocation(360,395);
        removeObject(wallHeightSmall21);
        WallHeightSmall wallHeightSmall22 = new WallHeightSmall();
        addObject(wallHeightSmall22,357,315);
        wallHeightSmall22.setLocation(358,322);
        WallHeightSmall wallHeightSmall23 = new WallHeightSmall();
        addObject(wallHeightSmall23,357,385);
        wallHeightSmall23.setLocation(359,394);
        WallWidthSmall wallWidthSmall18 = new WallWidthSmall();
        addObject(wallWidthSmall18,396,297);
        wallWidthSmall18.setLocation(394,298);
        WallHeightMedium wallHeightMedium4 = new WallHeightMedium();
        addObject(wallHeightMedium4,421,421);
        wallHeightMedium4.setLocation(412,408);
        WallWidthSmall wallWidthSmall19 = new WallWidthSmall();
        addObject(wallWidthSmall19,459,359);
        wallWidthSmall19.setLocation(449,356);
        WallHeightMedium wallHeightMedium5 = new WallHeightMedium();
        addObject(wallHeightMedium5,469,278);
        wallHeightMedium5.setLocation(471,294);
        MainCast mainCast = new MainCast();
        addObject(mainCast,273,35);
        MoveVertical moveVertical = new MoveVertical(2);
        addObject(moveVertical,99,215);
        MoveVertical moveVertical2 = new MoveVertical(2);
        addObject(moveVertical2,216,376);
        MoveVertical moveVertical3 = new MoveVertical(2);
        addObject(moveVertical3,273,317);
        MoveVertical moveVertical4 = new MoveVertical(2);
        addObject(moveVertical4,505,298);
        MoveVertical moveVertical5 = new MoveVertical(2);
        addObject(moveVertical5,389,240);
        MoveHorizontal moveHorizontal = new MoveHorizontal(1);
        addObject(moveHorizontal,243,94);
        removeObject(moveVertical5);
        MoveHorizontal moveHorizontal2 = new MoveHorizontal(1);
        addObject(moveHorizontal2,391,268);
        AddSpeed addSpeed = new AddSpeed();
        addObject(addSpeed,154,97);
        CheckPoint checkPoint = new CheckPoint();
        addObject(checkPoint,100,97);
        AddSpeed addSpeed2 = new AddSpeed();
        addObject(addSpeed2,38,440);
        CheckPoint checkPoint2 = new CheckPoint();
        addObject(checkPoint2,46,381);
        AddSpeed addSpeed3 = new AddSpeed();
        addObject(addSpeed3,155,502);
        CheckPoint checkPoint3 = new CheckPoint();
        addObject(checkPoint3,42,503);
        AddSpeed addSpeed4 = new AddSpeed();
        addObject(addSpeed4,329,335);
        addSpeed4.setLocation(324,303);
        CheckPoint checkPoint4 = new CheckPoint();
        addObject(checkPoint4,328,330);
        AddSpeed addSpeed5 = new AddSpeed();
        addObject(addSpeed5,446,42);
        AddSpeed addSpeed6 = new AddSpeed();
        addObject(addSpeed6,561,55);
        CheckPoint checkPoint5 = new CheckPoint();
        addObject(checkPoint5,562,108);
        AddSpeed addSpeed7 = new AddSpeed();
        addObject(addSpeed7,493,444);
        CheckPoint checkPoint6 = new CheckPoint();
        addObject(checkPoint6,444,408);
        AddSpeed addSpeed8 = new AddSpeed();
        addObject(addSpeed8,557,528);
        CheckPoint checkPoint7 = new CheckPoint();
        addObject(checkPoint7,560,556);
        checkPoint.setLocation(150,103);
        addSpeed.setLocation(160,96);
        addSpeed.setLocation(168,98);
        addSpeed.setLocation(149,91);
        checkPoint.setLocation(148,92);
        Flag flag = new Flag();
        addObject(flag,350,559);
        AddSpeed addSpeed9 = new AddSpeed();
        addObject(addSpeed9,271,139);
        removeObject(wallHeightSmall7);
        WallHeightSmall wallHeightSmall24 = new WallHeightSmall();
        addObject(wallHeightSmall24,181,375);
        wallHeightSmall24.setLocation(186,375);
        wallWidthLong.setLocation(115,8);
        removeObject(wallWidthLong);
        WallWidthLong wallWidthLong10 = new WallWidthLong();
        addObject(wallWidthLong10,99,7);
        wallWidthLong10.setLocation(100,8);
        CheckPoint checkPoint8 = new CheckPoint();
        addObject(checkPoint8,311,34);
        wallWidthSmall15.setLocation(318,67);
        wallWidthSmall15.setLocation(322,68);
        removeObject(wallWidthSmall15);
        WallWidthSmall wallWidthSmall20 = new WallWidthSmall();
        addObject(wallWidthSmall20,327,69);
        wallWidthSmall20.setLocation(328,66);
        removeObject(wallHeightSmall5);
        WallHeightSmall wallHeightSmall25 = new WallHeightSmall();
        addObject(wallHeightSmall25,304,553);
        wallHeightSmall25.setLocation(302,554);
        removeObject(wallHeightLong7);
        WallHeightLong wallHeightLong13 = new WallHeightLong();
        addObject(wallHeightLong13,527,108);
        wallHeightLong13.setLocation(533,108);
        wallHeightLong6.setLocation(586,405);
        removeObject(wallHeightLong6);
        WallHeightLong wallHeightLong14 = new WallHeightLong();
        addObject(wallHeightLong14,590,440);
        wallHeightLong14.setLocation(589,444);
        wallWidthLong2.setLocation(530,8);
        removeObject(wallWidthLong2);

        WallWidthLong wallWidthLong11 = new WallWidthLong();
        addObject(wallWidthLong11,494,9);
        wallWidthLong11.setLocation(497,10);

        removeObject(wallHeightSmall9);
        WallHeightSmall wallHeightSmall26 = new WallHeightSmall();
        addObject(wallHeightSmall26,84,452);
        wallHeightSmall26.setLocation(70,435);
        removeObject(wallWidthSmall9);
        WallWidthSmall wallWidthSmall21 = new WallWidthSmall();
        addObject(wallWidthSmall21,111,408);
        wallWidthSmall21.setLocation(106,412);
        removeObject(wallHeightSmall4);
        WallHeightSmall wallHeightSmall27 = new WallHeightSmall();
        addObject(wallHeightSmall27,409,54);
        wallHeightSmall27.setLocation(417,47);
        removeObject(wallWidthSmall17);
        WallWidthSmall wallWidthSmall22 = new WallWidthSmall();
        addObject(wallWidthSmall22,327,358);
        wallWidthSmall22.setLocation(337,358);
        removeObject(wallHeightSmall22);
        WallHeightSmall wallHeightSmall28 = new WallHeightSmall();
        addObject(wallHeightSmall28,373,331);
        wallHeightSmall28.setLocation(359,322);
        removeObject(wallWidthSmall18);
        WallWidthSmall wallWidthSmall23 = new WallWidthSmall();
        addObject(wallWidthSmall23,388,300);
        wallWidthSmall23.setLocation(389,298);
        removeObject(wallWidthSmall14);
        WallWidthSmall wallWidthSmall24 = new WallWidthSmall();
        addObject(wallWidthSmall24,279,182);
        wallWidthSmall24.setLocation(280,183);
        removeObject(wallWidthMedium5);
        removeObject(wallHeightMedium3);
        WallWidthMedium wallWidthMedium7 = new WallWidthMedium();
        addObject(wallWidthMedium7,119,66);
        wallWidthMedium7.setLocation(120,66);
        WallHeightMedium wallHeightMedium6 = new WallHeightMedium();
        addObject(wallHeightMedium6,62,127);
        wallHeightMedium6.setLocation(67,119);
        addSpeed.setLocation(148,98);
        addSpeed.setLocation(133,96);
        addSpeed.setLocation(135,86);
        checkPoint.setLocation(174,97);
        addSpeed.setLocation(155,92);
        checkPoint8.setLocation(275,47);
        checkPoint8.setLocation(278,18);
        mainCast.setLocation(278,48);
        removeObject(mainCast);
        MainCast mainCast2 = new MainCast();
        addObject(mainCast2,273,39);
        removeObject(wallWidthMedium4);
        WallWidthMedium wallWidthMedium8 = new WallWidthMedium();
        addObject(wallWidthMedium8,185,127);
        wallWidthMedium8.setLocation(191,124);
    }
}

